### PR TITLE
feat: add Docker support

### PR DESCRIPTION
**Pull request by echernyavskiy**
If the PR looks okay, perhaps you could also configure automated builds on [Docker hub](https://hub.docker.com/)?

### CODE REVIEW

**Comment by jthomerson** [comment]
Also: a note for @pbredenberg - when you get to the Node upgrade on this repo, we'd need to upgrade the version used in Docker

**Comment by echernyavskiy** [comment]
@jthomerson LGTM, thanks.

**Comment by jthomerson** [comment]
@echernyavskiy thanks. I published @silvermine/dynamodb-table-sync@1.2.0 with all your changes

**Comment by echernyavskiy** [comment]
@jthomerson, awesome, thanks! Any thoughts on also configuring automated builds on [Docker Hub](https://hub.docker.com/)?

**Comment by jthomerson** [comment]
@echernyavskiy that's something I'd be interested in doing, but we haven't ever published anything there before, and we're all pretty swamped with work right now, so I just don't have the time to even look into it right now. To do it right, I'm assuming we'd need to set up an organization there, with multiple of our team members having access, etc, etc.

Feel free to open an issue here if you'd like so we don't forget about the idea.

**Comment by echernyavskiy** [comment]
Yup, that's exactly right: create an organization and give Docker Hub access to Github. I'll create an issue, thanks.

**Pull request merged**
