### PR TITLE
feat: make retries configurable: --max-retries, --retry-delay-base

### PR DESCRIPTION
**Pull request by echernyavskiy**
See https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#constructor-property

### CODE REVIEW

**Comment by echernyavskiy** [comment]
@jthomerson could you please review this?

**Review by jthomerson — DISMISSED** [review]

**Review by jthomerson — APPROVED** [review]

**Comment by jthomerson** [comment]
@echernyavskiy sorry for the delay! I was away. This is now published to NPM in @silvermine/dynamodb-table-sync@1.3.0

**Comment by echernyavskiy** [comment]
@jthomerson awesome, thanks!
Could you please also tag these changes here on Github? Not seeing **1.3.0** here at the moment.

**Comment by jthomerson** [comment]
@echernyavskiy thanks! I forgot to push after publishing. Done now

**Pull request merged**
